version: 2
jobs:
  test:
    working_directory: ~/the-grid-ci
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run ci
  build:
    working_directory: ~/the-grid-ci
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Production Build
          command: npm run build
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
