version: 2

setup: &setup
  working_directory: ~/the-grid-ci
  docker:
    - image: circleci/node:8-browsers
jobs:
  checkout-and-install:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
            - the-grid-ci-{{ .Branch }}
            - the-grid-ci-
      - run: npm install --silent
      - save_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  test:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm run ci
  build:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Production Build
          command: npm run build
  deploy-staging:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Deploy
          command: |
            cd functions
            npm install --silent
            cd ..
            npm run deploy:staging
  deploy-prod:
    <<: *setup
    steps:
      - checkout
      - restore_cache:
          key: the-grid-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Deploy
          command: |
            cd functions
            npm install --silent
            cd ..
            npm run deploy:prod
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout-and-install
      - test:
          requires:
            - checkout-and-install
      - build:
          requires:
            - test
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /.*/
      - hold:
          type: approval
          requires:
            - build
      - deploy-prod:
          requires:
            - hold
